-- MySQL Script generated by MySQL Workbench
-- Sun May 11 02:09:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuário` (
  `id` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `foto_documento` LONGTEXT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id` VARCHAR(36) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Vendedor_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `Vendedor_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Produto_Usuário1_idx` (`Vendedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Usuário1`
    FOREIGN KEY (`Vendedor_id`)
    REFERENCES `mydb`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proposta de compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proposta de compra` (
  `id` VARCHAR(36) NOT NULL,
  `valor_proposto` DOUBLE NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Produto_id` VARCHAR(36) NOT NULL,
  `Comprador_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `Produto_id`, `Comprador_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Oferta_Produto1_idx` (`Produto_id` ASC) VISIBLE,
  INDEX `fk_Oferta_Usuário1_idx` (`Comprador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Oferta_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Usuário1`
    FOREIGN KEY (`Comprador_id`)
    REFERENCES `mydb`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id` VARCHAR(36) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `Oferta_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `Oferta_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Pedido_Oferta1_idx` (`Oferta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Oferta1`
    FOREIGN KEY (`Oferta_id`)
    REFERENCES `mydb`.`Proposta de compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentário` (
  `id` VARCHAR(36) NOT NULL,
  `texto` VARCHAR(200) NOT NULL,
  `resposta` VARCHAR(200) NULL,
  `Produto_id` VARCHAR(36) NOT NULL,
  `Comprador_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `Produto_id`, `Comprador_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Comentário_Produto_idx` (`Produto_id` ASC) VISIBLE,
  INDEX `fk_Comentário_Usuário1_idx` (`Comprador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comentário_Produto`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentário_Usuário1`
    FOREIGN KEY (`Comprador_id`)
    REFERENCES `mydb`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lista de desejos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lista de desejos` (
  `Comprador_id` VARCHAR(36) NOT NULL,
  `Produto_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`Comprador_id`, `Produto_id`),
  INDEX `fk_Usuário_has_Produto_Produto1_idx` (`Produto_id` ASC) VISIBLE,
  INDEX `fk_Usuário_has_Produto_Usuário1_idx` (`Comprador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_has_Produto_Usuário1`
    FOREIGN KEY (`Comprador_id`)
    REFERENCES `mydb`.`Usuário` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fotos` (
  `id` VARCHAR(36) NOT NULL,
  `base` LONGTEXT NOT NULL,
  `Produto_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`, `Produto_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Fotos_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria do produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria do produto` (
  `Categoria_id` VARCHAR(36) NOT NULL,
  `Produto_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`Categoria_id`, `Produto_id`),
  INDEX `fk_Categoria_has_Produto_Produto1_idx` (`Produto_id` ASC) VISIBLE,
  INDEX `fk_Categoria_has_Produto_Categoria1_idx` (`Categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_has_Produto_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categoria_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `mydb`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
